### ISSUE TITLE
Gsharp

### ISSUE THREAD

**Issue by ForthStar** [ad-si/awesome-sheet-music#2]
> Gsharp is an interactive, extensible editor for musical scores.

https://www.common-lisp.net/project/gsharp/

CC @csrhodes

**Comment by adius** [comment]
This doesn't seen to be maintained anymore and all links are broken.
Not sure this would be a good addition to the list …

**Comment by Trevoke** [comment]
The screenshots still work - though the git repo is unavailable, it seems.

It has potential, but it probably requires some legwork, like emailing a few folks to ascertain the actual state of the project.

**Comment by larsbrinkhoff** [comment]
I think @csrhodes is the maintainer.

**Comment by csrhodes** [comment]
Hm, I wonder why the git repo is unavailable.  I'll investigate.

**Comment by csrhodes** [comment]
There's a git repo and gitlab project at https://gitlab.common-lisp.net/gsharp/gsharp . You'll see that there hasn't been any recent development activity, but I believe the project is built every month and incorporated as part of quicklisp, which is probably the fastest way to get it up and running, if it does in fact up and run.  I can help if needed.

Other suggestions for your list: Gamera, an OMR toolkit framework; CMME, an editor for mensural notation

**Comment by larsbrinkhoff** [comment]
@adius Still no love for Gsharp?

**Comment by ad-si** [comment]
Still not totally convinced, but added Gsharp, Gamera, and CMME in b7568e7
