### ISSUE TITLE
add music-sheet-viewer

### ISSUE THREAD

**Issue by efreja** [ad-si/awesome-sheet-music#30]
https://wordpress.org/plugins/music-sheet-viewer/

**Comment by ad-si** [comment]
Added in 30d195e.

I also added partitionnumerique.com. Cool website, you should also provide it in English 😇

**Comment by efreja** [comment]
Thanks! For the translation of the website I have other priorities, and Google translate will do the trick for the ones interested. But thanks for the recommendation.
