### ISSUE TITLE
Add https://bayanguru.org/ to the archives section

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [ad-si/awesome-sheet-music#55]
Hi,

Could you, please, add the bayanguru web site to the free music scores section?

Web site: https://bayanguru.org/
GitHub: https://github.com/volodymyrprokopyuk/bayanguru

The author of the bayanguru site.

Thank you!

**Comment by ad-si** [comment]
Thanks! Added in b249781037af9c4d1128d5c7c5890fa331b823fd
